### PR TITLE
YARP_sig: add std::vector under the hood of yarp::sig::Vector

### LINKED ISSUE #2192: Problem with move semantic in yarp::sig::Vector
With the latest devel branch, running the wholeBodyDynamics on iCubGenova01 with `--autoconnect --no_legs --headV2` results in a crash in the following block:
https://github.com/robotology/icub-main/blob/b0c29f7890b82df3ae96759debf26c8246c8dbba/src/modules/wholeBodyDynamics/observerThread.cpp#L780-L803

tested with @xEnVrE @randaz81

### PR DESCRIPTION
**Pull request by Nicogene**
This PR get rid of `yarp::os::ManagedBytes` in `yarp::sig::Vector`.

It is just a draft for starting a discussion
It compiles and the tests passes.
And it fixes #2192 . (hopefully, it has to be tested).
Please review code.

### CODE REVIEW

**Comment by Nicogene** [comment]
Then the standard is not so standard https://travis-ci.org/robotology/yarp/jobs/646817743#L6871 :cry:

**Comment by Nicogene** [comment]
The failure of the test on macOs is quite interesting:

On linux if you have a vector of 10 elements, and then you resize it to 11,  you will have a vector of size 11 and capacity 11.

On macOs instead, it reserves 20 elements, and it uses 11, then size 11, capacity 20.

I thought that the standard was, when you resize of a bigger lenght, the allocation must be a power of 2 or similiar.

cc @drdanz @aerydna @traversaro @pattacini

**Comment by Nicogene** [comment]
Related posts https://stackoverflow.com/a/34811177 and https://stackoverflow.com/a/34101814.

It seems that **it doubles** the allocation, then 11>10-> allocates 20.

**Comment by pattacini** [comment]
@Nicogene we might need to relax the test to accommodate this lack of a standard. Eventually, how the OS handles the allocation shouldn't impact the user code as the relevant aspect of the API remains the size and not the capacity.

What do you think?

File: src/libYARP_sig/src/yarp/sig/Vector.h [hunk 1]
```diff
@@ -119,55 +120,30 @@ template<class T>
...
 public:
-    typedef T* iterator;
-    typedef const T* const_iterator;
 
     VectorOf() {
-        bytes.allocate(16*sizeof(T)); // preallocate space for 16 elements
-        bytes.setUsed(0);
-        first = nullptr;
-        len = 0;
+        bytes.reserve(16); // preallocate space for 16 elements
```
Comment (drdanz) [inline src/libYARP_sig/src/yarp/sig/Vector.h]: Do we still need this? I don't think we need to keep compatibility with the old behaviour

**Comment by traversaro** [comment]
I agree with @drdanz and @pattacini, the standard does not guarantee anything about how `reserve` allocates memory and how much memory it allocates, so the choice is either to remove the capacity test (or replace it with `capacity >= <value>`) or avoid to use the `std::vector`.

File: src/libYARP_sig/src/yarp/sig/Vector.h (hunk 1 above)
Comment (Nicogene) [reply src/libYARP_sig/src/yarp/sig/Vector.h]: In the past I saw people using empty `Vectors` to retrieve data from our interfaces, that it works because our vector it is initialize with 16 elements by defauit(max n of joints I suppose).

And I saw crashes when passing to std::vector. I know that it is a very bad practice, but changing the behaviour could make crash (bad)software here and there.

Comment (drdanz) [reply src/libYARP_sig/src/yarp/sig/Vector.h]: I think that's a sick behaviour, and we should not be allowed.

Comment (pattacini) [reply src/libYARP_sig/src/yarp/sig/Vector.h]: If the interface takes a Vector as input then it's its responsibility to allocate the necessary memory. Thus, I concur with @drdanz to remove the preallocation.

Moreover, if you declare
```c++
yarp::sig::Vector v;
```
`v` is assumed to be empty and e.g. `v[0]` will generate a run-time error already in the current behavior and that's ok.

Comment (Nicogene) [reply src/libYARP_sig/src/yarp/sig/Vector.h]: I put `yarp::sig::Vector() = default` then.

**Comment by Nicogene** [comment]
`WBD` tested with `demoRedBall` successfully

**Comment by drdanz** [comment]
Merged, thanks!
