### PR TITLE
imuBosch: fix conversion factor for gyro and magnetometer

### LINKED ISSUE #2038: imuBoschBNO055 has wrong conversion formulas for gyro and magnetometer
In the `imuBoschBNO055` [implementation](https://github.com/robotology/yarp/blob/master/src/devices/imuBosch_BNO055/imuBosch_BNO055.cpp) there are these conversion formulas:
```c++
        // Fill in accel values
        data_tmp[3] = (double)raw_data[0] / 100.0;
        data_tmp[4] = (double)raw_data[1] / 100.0;
        data_tmp[5] = (double)raw_data[2] / 100.0;


        // Fill in Gyro values
        data_tmp[6] = (double)raw_data[6] / 100.0;
        data_tmp[7] = (double)raw_data[7] / 100.0;
        data_tmp[8] = (double)raw_data[8] / 100.0;

        // Fill in Magnetometer values
        data_tmp[9]  = (double)raw_data[3] / 100.0;
        data_tmp[10] = (double)raw_data[4] / 100.0;
        data_tmp[11] = (double)raw_data[5] / 100.0;
```
Looking in the Bosch documentation the unit measure are for **gyro**:
image

and for **magnetometer**:
image

Then it seems that the values have to be divided by 16.0 instead 100.0.

I ran a simple test moving the joint 0 of the head up to 20 deg @ 20 deg/s recording the gyro

# BEFORE (using 100 as scaling factor)
image
# AFTER (using 16 as scaling factor)
image

### PR DESCRIPTION
**Pull request by Nicogene**
It fixes #2038

### CODE REVIEW

**Comment by Nicogene** [comment]
The statuses are broken, the links doesn't lead to the correct builds

File: src/devices/imuBosch_BNO055/imuBosch_BNO055.cpp [hunk 1]
```diff
@@ -619,14 +619,14 @@ void BoschIMU::run()
 
 
         // Fill in Gyro values
```
Comment (traversaro) [inline src/devices/imuBosch_BNO055/imuBosch_BNO055.cpp]: It would be great to have a link to the PDF datasheet with relative page number to document where that "16.0" value comes from.

**Comment by drdanz** [comment]
Merged, thanks.
