### PR TITLE
Various fixes rgbd sensors/wrapper

### LINKED ISSUE #1871: stereoMode and verbose parameters missing in realsense2 device docs
The `realsense2` device has a amazing docs in http://www.yarp.it/classyarp_1_1dev_1_1realsense2Driver.html . 
In this documentation, the options `verbose` and `stereoMode` (parsed in  https://github.com/robotology/yarp/blob/3d550be4ea1f51f7903a88f2279eaa85948f44df/src/devices/realsense2/realsense2Driver.cpp#L679 ) are not documented.

### LINKED ISSUE #1875: RGBDSensorWrapper example fails to run becasue fakeDepthCamera needs to implement yarp::dev::FrameGrabberControls
**Describe the bug**
The command described in https://github.com/robotology/yarp/blame/b7983c941952a3aafa7de7dd4aeeb574c1865799/example/dev/RGBD/README.md#L21 : 
~~~
yarpdev --device RGBDSensorWrapper --name /server --subdevice fakeDepthCamera --mode ball 
~~~
is failing with the following error:
~~~
straversaro@iiticublap103:~/src/idjl-superbuild/build3/idjl/YARP$ yarpdev --device RGBDSensorWrapper --name /server --subdevice fakeDepthCamera --mode ball 
[INFO]RGBDSensorWrapper: using default 'period' parameter of  0.03 s 
[INFO]RGBDSensorWrapper: ROS configuration parameters are not set, skipping ROS topic initialization. 
yarp: Port /server/rpc:i active at tcp://192.168.1.10:10007/
yarp: Port /server/rgbImage:o active at tcp://192.168.1.10:10008/
yarp: Port /server/depthImage:o active at tcp://192.168.1.10:10009/
[DEBUG]opening IRGBDSensor subdevice
[INFO]Test grabber period 0.0333333 / freq 30 , mode [ball]
[INFO]created device <test_grabber>. See C++ class yarp::dev::TestFrameGrabber for documentation.
[INFO]created device <fakeDepthCamera>. See C++ class yarp::dev::fakeDepthCameraDriver for documentation.
[ERROR]RGBD wrapper: error configuring interfaces for parsers 
[ERROR]RGBDSensorWrapper: error while opening subdevice
yarpdev: ***ERROR*** driver <RGBDSensorWrapper> was found but could not open
[ERROR]yarpdev: ***ERROR*** device not available.
[INFO]Suggestions:
[INFO]+ Do "yarpdev --list" to see list of supported devices.
[INFO]+ Or append "--verbose" option to get more information.
~~~

**Expected behavior**
The one described in the tutorial. 

**Configuration (please complete the following information):**
 - OS: Ubuntu 18.04
 - yarp version: current `devel` 
-  compiler: Gcc 7.3

### LINKED ISSUE #1877: RS2_OPTION_ACCURACY differs from our RGBD definition of accuracy
The RS2 parameter `RS2_OPTION_ACCURACY` should not be assigned to depth accuracy.

https://github.com/robotology/yarp/blob/2d160a4abb158e570d115d7774b29d06617bf981/src/devices/realsense2/realsense2Driver.cpp#L806

`RS2_OPTION_ACCURACY` is the number (integer) of point projected by the realsense to reconstruct depth. Our RGBD "accuracy" refers to the __resolution__ of the depth data.

Unless RS2 API provides a resolution type of information, we have to rethink this parameter.

### PR DESCRIPTION
**Pull request by Nicogene**
This PR:
- Fixes #1871
- Fixes #1875
- Fixes #1877 

Moreover it clarifies the documentation of (`set/getDepthAccuracy`).

Tests on real and fake device have been done.

Please review code.

### CODE REVIEW

File: src/libYARP_dev/include/yarp/dev/IVisualParams.h [hunk 1]
```diff
@@ -248,14 +249,14 @@ class YARP_dev_API yarp::dev::IDepthVisualParams
     virtual bool getDepthIntrinsicParam(yarp::os::Property &intrinsic) = 0;
 
     /**
-     * Get the accuracy of the depth measure in [meter]
```
Comment (traversaro) [inline src/libYARP_dev/include/yarp/dev/IVisualParams.h]: :+1:

File: src/libYARP_dev/include/yarp/dev/IVisualParams.h [hunk 2]
```diff
@@ -248,14 +249,14 @@ class YARP_dev_API yarp::dev::IDepthVisualParams
...
-     * @return the accuracy of the sensor in meters.
+     * Get the minimum detectable variation in distance [meter]
```
Comment (traversaro) [inline src/libYARP_dev/include/yarp/dev/IVisualParams.h]: :+1:
