### PR TITLE
Deprecate yarp::os::Value::operator==(const char *alt)

### LINKED ISSUE #1028: Value val == 0 gives SEGFAULT
```
    Value val = 1000;
    if (val == 0)
```
The == operator for values implicitly assumes that the right operand is a string, thus this kind of code gives segmentation fault.

C.f.r. line 268 of `yarp::os::Value::operator==`
```
 // comparisons with strings worked "accidentally", users depend on them
    bool operator==(const char *alt) const {
        return asString() == alt;
    }
```
This behaviour emerged using `bottle.get(n)` without `.asInt()`

### PR DESCRIPTION
**Pull request by aerydna**
fixes #1028.
`<yarp::os::Value> == <literal integer>` calls the `const char*` comparison overload (often resulting in a segfault). new `int` comparison overload has been added with relative test.

### CODE REVIEW

File: src/libYARP_OS/include/yarp/os/Value.h [hunk 1]
```diff
@@ -276,6 +276,16 @@ class YARP_OS_API yarp::os::Value : public Portable, public Searchable {
         return asString() != alt;
     }
 
+    bool operator==(const int alt) const
```
Comment (randaz81) [inline src/libYARP_OS/include/yarp/os/Value.h]: why are we not removing the bool operator==(const char *alt) mess?

Comment (randaz81) [inline src/libYARP_OS/include/yarp/os/Value.h]: Have you evaluated the impact of removing the == operator (simply counting the number of uses (i.e. errors) by commenting out the operator?

Comment (randaz81) [inline src/libYARP_OS/include/yarp/os/Value.h]: Additional considerations for multipurpose data-type like value: operator == always generates problems and should be generally avoided. What happens for example if the value internally stored was a double? With this commit you will allow users to compare it with an int. The comparison is ok (more or less), but I fear it may generate other misusage problems in the future...

File: tests/libYARP_OS/ValueTest.cpp [hunk 2]
```diff
@@ -235,6 +235,11 @@ class ValueTest : public UnitTest {
             checkTrue((v1!=v2), "(blob) operator!= ok");
             checkTrue((v1!=*(reinterpret_cast<const int*>(v2.asBlob()))), "(blob) value ok");
         }
+
+        {
+            Value v(0);
+            checkTrue(v == 0, "equivalence with integer literal ok");
```
Comment (randaz81) [inline tests/libYARP_OS/ValueTest.cpp]: Unclear to me: what we want to test here?
According to the lately introduced `YARP_DEPRECATED_MSG`, shouldn't this be `v.asInt() == 0`?

**Comment by randaz81** [comment]
Rebase requested

File: tests/libYARP_OS/ValueTest.cpp (hunk 2 above)
Comment (aerydna) [inline tests/libYARP_OS/ValueTest.cpp]: i've simply forgot to delete the test

**Comment by randaz81** [comment]
Rebase requested

**Comment by drdanz** [comment]
What happened here? You removed the deprecation stuff and restored the first version of the patch...

**Comment by drdanz** [comment]
FYI we deleted the branch and force pushed the merge with the correct version of the patch.
