### PR TITLE
Try to fix NodeTest race condition

### LINKED ISSUE #374: OS::NodeTest failed on travis
`NodeTest` failed on travis, without code change - it may be revealing a race?

  * https://travis-ci.org/robotology/yarp/jobs/47929078

### PR DESCRIPTION
**Pull request by drdanz**
`YARP_serversql/NameServiceOnTriples`: Protect concurrent access to internal variables using a mutex

Fixes several race conditions reported by valgrind

Might fix #374 

CC @Tobias-Fischer
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/860%23discussion_r73843846%22%2C%20%22https%3A//github.com/robotology/yarp/pull/860%23issuecomment-238182507%22%2C%20%22https%3A//github.com/robotology/yarp/pull/860%23discussion_r73850323%22%2C%20%22https%3A//github.com/robotology/yarp/pull/860%23issuecomment-238213020%22%2C%20%22https%3A//github.com/robotology/yarp/pull/860%23issuecomment-238221280%22%2C%20%22https%3A//github.com/robotology/yarp/pull/860%23issuecomment-238221454%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/860%23issuecomment-238182507%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%27ll%20let%20the%20test%20run%20for%20a%20couple%20of%20hours%20and%20report%20whether%20it%20runs%20fine.%22%2C%20%22created_at%22%3A%20%222016-08-08T09%3A12%3A47Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40Tobias-Fischer%20I%27ve%20run%20it%20locally%20for%20a%20few%20hours%20with%20no%20crashes%2C%20any%20crash%20on%20your%20side%3F%20Otherwise%20I%27m%20merging%20this...%22%2C%20%22created_at%22%3A%20%222016-08-08T11%3A47%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22No%20crashes%20here%20for%203%20or%204%20hours%20..%20Go%20ahead%20and%20merge%20I%27d%20say%20%3A%29%22%2C%20%22created_at%22%3A%20%222016-08-08T12%3A30%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-08-08T12%3A31%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%2C%20%22Pull%20e6da8fe6c4d002971c0e210ed920ccb665bc147d%20src/libYARP_serversql/src/NameServiceOnTriples.h%2011%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/860%23discussion_r73843846%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22This%20might%20be%20a%20good%20chance%20to%20also%20use%20proper%20initializers%20for%20the%20other%20attributes%20..%22%2C%20%22created_at%22%3A%20%222016-08-08T09%3A11%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%5Cr%5CnDone%2C%20thanks%22%2C%20%22created_at%22%3A%20%222016-08-08T09%3A59%3A56Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20src/libYARP_serversql/src/NameServiceOnTriples.h%3AL57-69%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-Pull e6da8fe6c4d002971c0e210ed920ccb665bc147d src/libYARP_serversql/src/NameServiceOnTriples.h 11'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/860#discussion_r73843846'>File: src/libYARP_serversql/src/NameServiceOnTriples.h:L57-69</a></b>
- <a href='https://github.com/Tobias-Fischer'></a> This might be a good chance to also use proper initializers for the other attributes ..
- <a href='https://github.com/drdanz'></a> :+1:
Done, thanks
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/860#issuecomment-238182507'>General Comment</a></b>
- <a href='https://github.com/Tobias-Fischer'></a> I'll let the test run for a couple of hours and report whether it runs fine.
- <a href='https://github.com/drdanz'></a> @Tobias-Fischer I've run it locally for a few hours with no crashes, any crash on your side? Otherwise I'm merging this...
- <a href='https://github.com/Tobias-Fischer'></a> No crashes here for 3 or 4 hours .. Go ahead and merge I'd say :)

<a href='https://www.codereviewhub.com/robotology/yarp/pull/860?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/860?approve=1'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/860'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/860'>Refresh</a>.<a href='#crh-update-none'></a>

File: src/libYARP_serversql/src/NameServiceOnTriples.h [hunk 1]
```diff
@@ -57,12 +57,12 @@ class NameServiceOnTriples : public yarp::name::NameService {
...
     std::string lastRegister;
     yarp::os::Contact serverContact;
-    yarp::os::Semaphore mutex;
+    yarp::os::Semaphore mutex, access;
     bool gonePublic;
     bool silent;
     yarp::os::NameSpace *delegate;
 public:
-    NameServiceOnTriples() : mutex(1) {
+    NameServiceOnTriples() : mutex(1), access(1) {
```
Comment (Tobias-Fischer) [inline src/libYARP_serversql/src/NameServiceOnTriples.h]: This might be a good chance to also use proper initializers for the other attributes ..

**Comment by Tobias-Fischer** [comment]
I'll let the test run for a couple of hours and report whether it runs fine.

File: src/libYARP_serversql/src/NameServiceOnTriples.h (hunk 1 above)
Comment (drdanz) [inline src/libYARP_serversql/src/NameServiceOnTriples.h]: :+1:
Done, thanks

**Comment by drdanz** [comment]
@Tobias-Fischer I've run it locally for a few hours with no crashes, any crash on your side? Otherwise I'm merging this...

**Comment by Tobias-Fischer** [comment]
No crashes here for 3 or 4 hours .. Go ahead and merge I'd say :)

**Comment by Tobias-Fischer** [comment]
:+1:

**Comment by drdanz** [comment]
@Tobias-Fischer thanks for testing!
