### PR TITLE
Fix double to string conversion (impacts timestamps) 

### LINKED ISSUE #1397: Broken handling of timestamp of robot motor ports
I've verified that 6ecffb7163fa380a98066bf7d58fa0d42878c9e9 (i.e. `devel` at the time of writing) show a **critical bug** 🐞 in the handling of the timestamp attached to the robot motor ports.

The timestamp on the robot does not increment, remaining frozen, while on `iCub_Sim` the timestamp deltas are only of `1s each` - strangely.

The test can be run easily via:
```sh
$ yarp read ... /[icub|icubSim]/head/state:o envelope
```

Alternatively, you can connect the dumper:
```sh
$ yarpdatadumper --connect /[icub|icubSim]/head/state:o
```
and then explore the content of the file containing the logged data.

cc @vvasco @traversaro @francesco-romano @claudiofantacci @drdanz @aerydna

### PR DESCRIPTION
**Pull request by barbalberto**
This PR change doubleToString in order to generate the shortest string in terms of characters, while printing maximum achievable double precision.
Examples:

 0.00000000000001  will be printed as  1e-13 
 12345678.90123     will be printed as  12345678.90123 
 1234567890123456789    will be printed as    1.23456789012346e+19 

It fixes #1397

### CODE REVIEW

**Comment by barbalberto** [comment]
Yes, next step is to understand why timestamps are sent as string... and fix it.
Meanwhile at least they are correct

**Comment by traversaro** [comment]
> Yes, next step is to understand why timestamps are sent as string... and fix it. 

😍

File: src/libYARP_OS/src/BottleImpl.cpp [hunk 1]
```diff
@@ -805,7 +805,7 @@ bool StoreVocab::writeRaw(ConnectionWriter& writer)
 ConstString StoreDouble::toString() const
 {
     char buf[512];
-    sprintf(buf, "%g", x);
+    sprintf(buf, "%.*g", DBL_DIG, x);
```
Comment (traversaro) [inline src/libYARP_OS/src/BottleImpl.cpp]: Per [`iwyu`](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhyIWYU.md), I would add an `#include <cfloat>` to this file to avoid unexpected breakages in the future.

File: src/libYARP_OS/src/BottleImpl.cpp [hunk 2]
```diff
@@ -817,21 +817,6 @@ ConstString StoreDouble::toString() const
...
-            if (str[i - 1] == '.') {
-                ct--;
-                i++;
-            }
-            if (ct >= 1) {
-                str = str.substr(0, i);
-            }
-            break;
-        }
-        ct++;
```
Comment (traversaro) [inline src/libYARP_OS/src/BottleImpl.cpp]: Why this disappeared?

File: src/libYARP_OS/src/BottleImpl.cpp [hunk 3]
```diff
@@ -817,21 +817,6 @@ ConstString StoreDouble::toString() const
     } else {
```
Comment (traversaro) [inline src/libYARP_OS/src/BottleImpl.cpp]: Whoa, not related to this fix but I did not know that YARP had something in place to deal with problems like https://github.com/robotology/idyntree/issues/288 .

Comment (traversaro) [reply src/libYARP_OS/src/BottleImpl.cpp]: And apparently is a part that needs to be modified to compile on Android: https://alecive.github.io/blog/2015/08/31/YARP-Cross-Compilation/ .

File: src/libYARP_OS/src/BottleImpl.cpp (hunk 2 above)
Comment (claudiofantacci) [reply src/libYARP_OS/src/BottleImpl.cpp]: By my understanding (cc @Nicogene) `sprintf(buf, "%.*g", DBL_DIG, x);` with the specific `%.*g` argument automatically accounts for removing trailing zeros.

**Comment by traversaro** [comment]
Related issue to envelope set as a string: https://github.com/robotology/yarp/issues/353 .

**Comment by claudiofantacci** [comment]
@traversaro whoa about [#353](https://github.com/robotology/yarp/issues/353) 😮 
I would expect some benefits on the PC104 indeed (and only CP104?...maybe not...) once we have no string convertions.

File: src/libYARP_OS/src/BottleImpl.cpp (hunk 2 above)
Comment (barbalberto) [reply src/libYARP_OS/src/BottleImpl.cpp]: right! That code was manually removing trailing zeros, while `%g` does not print them in the first place.

**Comment by barbalberto** [comment]
@Nicogene Done, thanks

File: src/libYARP_OS/src/BottleImpl.cpp (hunk 1 above)
Comment (barbalberto) [reply src/libYARP_OS/src/BottleImpl.cpp]: Done!

File: src/libYARP_OS/src/BottleImpl.cpp [hunk 4]
```diff
@@ -805,7 +806,7 @@ bool StoreVocab::writeRaw(ConnectionWriter& writer)
 ConstString StoreDouble::toString() const
 {
     char buf[512];
-    sprintf(buf, "%g", x);
+    sprintf(buf, "%.*g", DBL_DIG, x);
```
Comment (drdanz) [inline src/libYARP_OS/src/BottleImpl.cpp]: Is this guaranteed to fit in 512 bytes?
I wonder if, due to double imprecision error could become something like 1.000000...0000042523623 and cause a buffer overflow...
Maybe, since you are touching this part, it would be better to use
```c++
snprintf(buf, 511, "%.*g", DBL_DIG, x);
buf[511]='\0';
```

File: src/libYARP_OS/src/BottleImpl.cpp (hunk 2 above)
Comment (traversaro) [reply src/libYARP_OS/src/BottleImpl.cpp]: Ok, thanks!

File: src/libYARP_OS/src/BottleImpl.cpp (hunk 4 above)
Comment (Nicogene) [reply src/libYARP_OS/src/BottleImpl.cpp]: :+1:  I agree with @drdanz

Comment (traversaro) [reply src/libYARP_OS/src/BottleImpl.cpp]: > What if instead we substitute the char buf[512]; with
char *buf = new char[DBL_DIG+2+EXP_DIG + 1]; ?

If both `DBL_DIG` and `EXP_DIG` are macros, we can still have a stack-allocated array avoiding a memor allocation in the heap.

Comment (claudiofantacci) [reply src/libYARP_OS/src/BottleImpl.cpp]: I tried
```bash
touch myfile.c
gcc -std=c11 -E -dM myfile.c
clang -std=c11 -E -dM myfile.c
```
and I found `#define DBL_DIG 15`, but not trace of `EXP_DIG`.
@barbalberto which macro you are referring at?
This is exactly the kind of issue you raised in the end, isn't it?

Comment (barbalberto) [reply src/libYARP_OS/src/BottleImpl.cpp]: Yes, `EXP_DIG` doesn't exist, so we need to define it if we want to implement this solution.
The file `float.c` defines `DBL_MAX_EXP` as an integer, like 999. What is missing is that 999 has 3 digits. It can be get easily with something like `log10(DBL_MAX_EXP)`.

Comment (claudiofantacci) [reply src/libYARP_OS/src/BottleImpl.cpp]: I see. Let's see what the others think about it.
Beware that doing something like `log10(DBL_MAX_EXP)` to get the number of digits of the exponents is somewhat tricky.

**Comment by pattacini** [comment]
A general comment from my side.

If possible it'd be way better to use C++\C++11 and `std::string` instead of struggling with C-like routines to deal with text, especially considering that we all agree that in the (near) future it's somewhat paramount to replace text with proper numbers while sending the envelope.

File: src/libYARP_OS/src/BottleImpl.cpp (hunk 4 above)
Comment (drdanz) [reply src/libYARP_OS/src/BottleImpl.cpp]: @barbalberto Great! Thanks for the detailed explaination. I agree that if it is safe to use a smaller buffer, it does not make sense to use a 512
I added a commit with some CMake magic to get that number, feel free to trash it if you don't want to use it... The commit adds 3 defines in `<yarp/conf/numeric.h>`

```c++
#define YARP_FLT_EXP_DIG @YARP_FLT_EXP_DIG@
#define YARP_DBL_EXP_DIG @YARP_DBL_EXP_DIG@
#define YARP_LDBL_EXP_DIG @YARP_LDBL_EXP_DIG@
```

I used `YARP_DBL_EXP_DIG` instead of `EXP_DIG` because macros are evil, namespacing them is always a good idea 😬 

I still believe that it would be better to use `snprintf` instead of `printf`

Comment (barbalberto) [reply src/libYARP_OS/src/BottleImpl.cpp]: :+1:  
I agree on both your suggestions. I'll update the commit using `snprintf` and `YARP_` prefixed name, so then we can merge it. :tada:

**Comment by barbalberto** [comment]
Updated and rebased

File: src/libYARP_OS/src/BottleImpl.cpp [hunk 5]
```diff
@@ -43,6 +44,22 @@ using yarp::os::Value;
...
+ * '.' decimal separator char               1 char
+ *  DBL_DIG digits for the mantissa         DBL_DIG chars
+ * 'e+/-'                                   2 chars
+ * YARP_DBL_EXP_DIG  for the exponential    YARP_DBL_EXP_DIG chars
+ * string terminator                        1 char
+ * FILLER                                   10 chars  (you know, for safety)
+ * -----------------------------------------------------
+ * TOTAL is                                 16 + DBL_DIG + YARP_DBL_EXP_DIG
+ */
+#define YARP_DOUBLE_TO_STRING_MAX_LENGHT       16+ DBL_DIG +YARP_DBL_EXP_DIG
```
Comment (gsaponaro) [inline src/libYARP_OS/src/BottleImpl.cpp]: small typo: lenght -> length

Comment (claudiofantacci) [reply src/libYARP_OS/src/BottleImpl.cpp]: 🙃

Comment (claudiofantacci) [reply src/libYARP_OS/src/BottleImpl.cpp]: And...I know I will sound peaky but... could you please also add some spaces in the `#define`, just like it is written in `TOTAL is`.

Comment (barbalberto) [reply src/libYARP_OS/src/BottleImpl.cpp]: Ops, I did it again

**Comment by barbalberto** [comment]
@claudiofantacci do you mean to vertically align the `16 + ... ` on the two lines?

**Comment by claudiofantacci** [comment]
Eheh, don't worry, I meant `16 + DBL_DIG + YARP_DBL_EXP_DIG`. But really, doesn't matter.

**Comment by barbalberto** [comment]
Done and fixed typo

File: src/libYARP_OS/src/BottleImpl.cpp [hunk 6]
```diff
@@ -42,6 +44,22 @@ using yarp::os::Value;
...
+ * '.' decimal separator char               1 char
+ *  DBL_DIG digits for the mantissa         DBL_DIG chars
+ * 'e+/-'                                   2 chars
+ * YARP_DBL_EXP_DIG  for the exponential    YARP_DBL_EXP_DIG chars
+ * string terminator                        1 char
+ * FILLER                                   10 chars  (you know, for safety)
+ * -----------------------------------------------------
+ * TOTAL is                                 16 + DBL_DIG + YARP_DBL_EXP_DIG
+ */
+#define YARP_DOUBLE_TO_STRING_MAX_LENGTH    16 + DBL_DIG + YARP_DBL_EXP_DIG
```
Comment (drdanz) [inline src/libYARP_OS/src/BottleImpl.cpp]: I wonder if it would be better to use some constexpr magic to calculate the first power of 2 bigger than this expression (or just throw away everything and use 64). AFAIK arrays of size that is a power of 2 can be optimized better by the compiler...

File: src/libYARP_OS/src/BottleImpl.cpp [hunk 7]
```diff
@@ -804,8 +822,8 @@ bool StoreVocab::writeRaw(ConnectionWriter& writer)
 
 ConstString StoreDouble::toString() const
 {
-    char buf[512];
-    sprintf(buf, "%g", x);
+    char buf[YARP_DOUBLE_TO_STRING_MAX_LENGTH];    // -> see comment at the top of the file
+    snprintf(buf, YARP_DOUBLE_TO_STRING_MAX_LENGTH, "%.*g", DBL_DIG, x);
```
Comment (drdanz) [inline src/libYARP_OS/src/BottleImpl.cpp]: This is pedantic, but `snprintf` is not guaranteed to set `/0` as the last character if the size of the produced string is greater than the size of the array, and static analysis tools will complain.
Please use:
```cpp
snprintf(buf, YARP_DOUBLE_TO_STRING_MAX_LENGTH - 1, "%.*g", DBL_DIG, x);
buf[YARP_DOUBLE_TO_STRING_MAX_LENGTH - 1] = '\0';

Comment (claudiofantacci) [reply src/libYARP_OS/src/BottleImpl.cpp]: @drdanz really it is not guaranteed? The documentations says that: `At most buf_size - 1 (for us is YARP_DOUBLE_TO_STRING_MAX_LENGTH - 1 ) characters are written. The resulting character string will be terminated with a null character.`
What am I misunderstanding here?

Comment (drdanz) [reply src/libYARP_OS/src/BottleImpl.cpp]: `should` be...
Unfortunately have a look at https://stackoverflow.com/questions/7706936/is-snprintf-always-null-terminating

Comment (drdanz) [reply src/libYARP_OS/src/BottleImpl.cpp]: Actually, at a second thought, I don't know if we are actually using `_snprintf` underneath
I think we should be using `std::snprintf` (that is guaranteed to have the terminating character) to ensure that we are not using some magic `#define`. I'm not 100% sure that it is supported in VS2013 though...

Comment (claudiofantacci) [reply src/libYARP_OS/src/BottleImpl.cpp]: I see. Anyway, shouldn't we always (or at least at the best of our possibilities) use C++ functions? I would use std::snprintf and also test it on different systems.

**Comment by drdanz** [comment]
Changed snprintf -> std::snprintf
I'll wait for the tests before merging, just to be sure that it is supported everywhere...

**Comment by drdanz** [comment]
VS2013: 'snprintf' : is not a member of 'std' 💩

**Comment by claudiofantacci** [comment]
> VS2013: 'snprintf' : is not a member of 'std' 💩

Yet another reason to drop support for VS13 (cfr #1035).

**Comment by drdanz** [comment]
Ok, next try...

```c++
#if defined(_MSC_VER) && (_MSC_VER <= 1800)
    // Visual Studio 2013 does not support std::snprintf
    _snprintf(buf, YARP_DOUBLE_TO_STRING_MAX_LENGTH - 1, "%.*g", DBL_DIG, x);
    buf[YARP_DOUBLE_TO_STRING_MAX_LENGTH -1] = '\0';
#else
    std::snprintf(buf, YARP_DOUBLE_TO_STRING_MAX_LENGTH, "%.*g", DBL_DIG, x);
#endif
```

Let's see if it works this time

It's probably pedantic, but I don't like not knowing which function is actually called... Also this will help us remember that we can remove this part when we drop support for VS 2013

**Comment by pattacini** [comment]
We should fix the bug asap...

**Comment by claudiofantacci** [comment]
@drdanz all test passed correctly, we should merge it 😄

**Comment by drdanz** [comment]
Merged, thanks.

**Comment by drdanz** [comment]
Can we close #1397 and #1415 now?
