### PR TITLE
Bugfix for yarpdev on Windows

### LINKED ISSUE #1357: On Windows "yarpdev --list" command results in segmentation fault.
The program is blocked while trying to split the text describing devices:
```
Device "test_motor", C++ class yarp::dev::TestMotor, wrapped by "controlboard"
Device "remote_grabber", C++ class yarp::dev::RemoteFrameGrabber, wrapped by "grabber"
Device "grabber", C++ class yarp::dev::ServerFrameGrabber, is a network wrapper.
...
```
into lines with single device. It stops on the invocation of  getline function from ConstString class:
```
    inline std::istream& getline(std::istream& is, yarp::os::ConstString& str, char delim) {
        return getline(is, (std::string&)str, delim);
    }
```
where `is` seems to be void.

### PR DESCRIPTION
**Pull request by damn1**
Fix `yarp::os::ConstString::getline(...)` to work fine with Windows.
It fixes #1357.

### CODE REVIEW

File: src/libYARP_OS/include/yarp/os/ConstString.h [hunk 1]
```diff
@@ -582,11 +582,25 @@ namespace std {
     }
 
     inline std::istream& getline(std::istream& is, yarp::os::ConstString& str, char delim) {
+#ifdef YARP_WRAP_STL_STRING_INLINE
         return getline(is, (std::string&)str, delim);
+#else
+		std::string line;
+		getline(is, line, delim);
+		str = line;
+		return is;
```
Comment (drdanz) [inline src/libYARP_OS/include/yarp/os/ConstString.h]: Ahhhhhh 💥 💀 
Please remove the tabs.

File: src/libYARP_OS/include/yarp/os/ConstString.h [hunk 2]
```diff
@@ -582,11 +582,25 @@ namespace std {
...
+#endif
     }
 
     inline std::istream& getline(std::istream& is, yarp::os::ConstString& str) {
-        return getline(is, (std::string&)str);
+#ifdef YARP_WRAP_STL_STRING_INLINE
+		return getline(is, (std::string&)str);
```
Comment (drdanz) [inline src/libYARP_OS/include/yarp/os/ConstString.h]: tab

File: src/libYARP_OS/include/yarp/os/ConstString.h [hunk 3]
```diff
@@ -582,11 +582,25 @@ namespace std {
...
+#else
+		std::string line;
+		getline(is, line);
+		str = line;
+		return is;
```
Comment (drdanz) [inline src/libYARP_OS/include/yarp/os/ConstString.h]: tabs

File: src/libYARP_OS/include/yarp/os/ConstString.h (hunk 1 above)
Comment (damn1) [reply src/libYARP_OS/include/yarp/os/ConstString.h]: sorry :sweat: didn't see them in VS

**Comment by drdanz** [comment]
Merged, thanks.
